version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nest_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_service_container
    environment:
      - PORT
      - MYSQL_HOST 
      - MYSQL_PORT 
      - MYSQL_USER 
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql_data:

